### PR TITLE
GPII-3492: Allow us to (optionally) prevent destruction of the cluster. (exekube)

### PR DESCRIPTION
**Pull request by mrtyler**
Prerequisite for https://github.com/gpii-ops/gpii-infra/pull/199.

- [ ] This change should also be proposed to upstream.

### CODE REVIEW

**Comment by amatas** [comment]
LGTM

**Comment by stepanstipl** [comment]
lgtm

**Comment by natarajaya** [comment]
LGTM

**Comment by mrtyler** [comment]
Upstream PR:
https://github.com/exekube/exekube/pull/112

**Pull request merged**
