### PR TITLE
[GPII-3898]:  Add istioctl to google image

### PR DESCRIPTION
**Pull request by natarajaya**

### CODE REVIEW

**Comment by natarajaya** [comment]
@mrtyler Should I manually push `0.6.1-google_gpii.0` tag to GitLab once this merged?

**Comment by mrtyler** [comment]
LGTM though I might have gone to 0.7.0 for this change.

> Should I manually push 0.6.1-google_gpii.0 tag to GitLab once this merged?

I think you want to push it to github and let it sync over to gitlab, but yes.

**Comment by stepanstipl** [comment]
lgtm.

**Comment by natarajaya** [comment]
> LGTM though I might have gone to 0.7.0 for this change

I think it makes sense, since the change adds new functionality.

**Comment by natarajaya** [comment]
Upstream PR: https://github.com/exekube/exekube/pull/125

**Pull request merged**
