### PR TITLE
GPII-3860: Bin Auth plumbing

### PR DESCRIPTION
**Pull request by mrtyler**
This PR replaces https://github.com/gpii-ops/exekube/pull/45 since I needed to fix conflicts and add a version bump and I can't do that on Sergey's branch.

This PR is built on top of https://github.com/gpii-ops/exekube/pull/52 so that I don't have to resolve conflicts again. The last 3 commits are the relevant ones.

This change is proposed to upstream: https://github.com/exekube/exekube/pull/123

### CODE REVIEW

**Comment by stepanstipl** [comment]
Should the version in `cli/main.go` be bumped to `0.5.1` too? (There's a good pattern for this in go to set the version at build time from env variable using `-ldflags` option).

LGTM.

**Comment by mrtyler** [comment]
The CLI tool didn't change, so I didn't change its version.

Since my current project is about updating our fork to the latest (actually it's not even that -- it's about enabling Binary Auth in GKE clusters), I won't refactor how the CLI tool is built at this time.

**Comment by mrtyler** [comment]
Updated to include the upstream merge of https://github.com/exekube/exekube/pull/123 (one fewer commit to worry about for the next upstream sync).

**Comment by mrtyler** [comment]
Tagged 0.5.1-google_gpii.0.

**Pull request merged**
