### PR TITLE
[GPII-4057]: Lock gem versions with bundler

### PR DESCRIPTION
**Pull request by natarajaya**
This is a follow-up on https://github.com/gpii-ops/gpii-infra/pull/472.
This also bumps Stackdriver gems to latest versions.

### CODE REVIEW

**Comment by mrtyler** [comment]
LGTM

I guess this should go to upstream as well.

FYI in case it comes up: I've had trouble with these google gems in the past: https://github.com/gpii-ops/gpii-infra/blob/master/shared/rakefiles/tests/Gemfile#L11

**Comment by stepanstipl** [comment]
Thanks for doing this @natarajaya, LGTM.

I think you'll need a new version, `0.9.3` has already been used in https://github.com/gpii-ops/exekube/pull/66.

Note: I noticed this adds another 30M to our (already huge ;() exekube image:
```
gpii/exekube                             0.9.3-google_gpii.0      986f196442d5        26 hours ago        1.17GB
# image from this PR
gpii-ops/exekube                         gems                     516408248f3f        2 hours ago         1.2GB
```

> I guess this should go to upstream as well.

@mrtyler given upstream does not have Ruby at all... how?

**Comment by mrtyler** [comment]
Oops, I forgot that ruby is only for us. Ignore the request to upstream.

**Comment by natarajaya** [comment]
Thanks for reviews!

> FYI in case it comes up: I've had trouble with these google gems in the past

@mrtyler Nice catch! Since we bundle gems in exekube now, I had to add rspec into separate group and remove gemfiles from gpii-infra.

**Pull request merged**
