### PR TITLE
[GPII-3639] Add upgrade option to helm init

### PR DESCRIPTION
**Pull request by amatas**
Full description here:

https://issues.gpii.net/browse/GPII-3639

I've rerun rake command several times and seems to work fine.

I have deployed a cluster with an old version of Helm. Then I've updated the Helm version in the exekube image and the Tiller was upgraded in the next execution. No new updates triggered in the next executions.

### CODE REVIEW

**Comment by stepanstipl** [comment]
@amatas Tiller install is currently only triggered when needed (ie. theres no running replica based on the `data.external.tiller_status.result.readyReplicas` status). While this is desirable, as we don't want to run this every time, I believe it would prevent this fix from having any effect on a cluster with existing Tiller installation.

On a first though solution to this might be introducing helm version (either hardcoded or from `helm version` - need to think about implications here) as additional trigger.

**Comment by mrtyler** [comment]
LGTM

**Comment by stepanstipl** [comment]
Yep, this looks good! 👍

**Comment by natarajaya** [comment]
LGTM!

**Pull request merged**
