### PR TITLE
[GPII-3641]: Add option to enable binary authorization into gke-cluster

### PR DESCRIPTION
**Pull request by natarajaya**

### CODE REVIEW

**Comment by mrtyler** [comment]
LGTM

**Comment by mrtyler** [comment]
I guess this should be proposed to upstream as well.

**Comment by stepanstipl** [comment]
LGTM

**Comment by amatas** [comment]
LGTM

**Comment by mrtyler** [comment]
Closing in favor of https://github.com/gpii-ops/exekube/pull/53

**Pull request closed without merging**
